name: Release

on:
  push:
    tags:
      - "[vV]*"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml

  release:
    name: Release
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dinput8.dll
          path: staging

      - name: Copy configuration files
        shell: pwsh
        run: >
          Copy-Item "patches.txt" -Destination "staging/"

      - name: Package artifact
        shell: pwsh
        run: >
          Compress-Archive -Path "staging/*" -DestinationPath "osgt-qol-${{ github.ref_name }}.zip" -Force

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: osgt-qol-${{ github.ref_name }}.zip
          generate_release_notes: true
          # Create a draft so we can replace the changelogs manually prior to publishing
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
